//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmtMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmtexamflag
    {
        public int flagid { get; set; }
        public Nullable<int> flagcount { get; set; }
        public string flagerror { get; set; }
        public int examid { get; set; }
    
        public virtual mmtexam mmtexam { get; set; }
    }
}
