//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmtMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMT_ConstEntities : DbContext
    {
        public MMT_ConstEntities()
            : base("name=MMT_ConstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mmtexamflag> mmtexamflags { get; set; }
        public virtual DbSet<mmtexam> mmtexams { get; set; }
        public virtual DbSet<mmtgroup> mmtgroups { get; set; }
        public virtual DbSet<mmtquestionbank> mmtquestionbanks { get; set; }
        public virtual DbSet<mmtsection> mmtsections { get; set; }
        public virtual DbSet<mmttopic> mmttopics { get; set; }
    }
}
