//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmtMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmtquestionbank
    {
        public int questionid { get; set; }
        public string question { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string f { get; set; }
        public string g { get; set; }
        public string h { get; set; }
        public string cols { get; set; }
        public string rows { get; set; }
        public string ans { get; set; }
        public string qtype { get; set; }
        public int topicid { get; set; }
        public int secid { get; set; }
        public int sectionid { get; set; }
        public int examid { get; set; }
        public int difficulty { get; set; }
        public string textanswer { get; set; }
        public string figure { get; set; }
        public string sound { get; set; }
        public string video { get; set; }
        public int passageId { get; set; }
        public string status { get; set; }
        public int score { get; set; }
        public int groupid { get; set; }
        public bool calculator { get; set; }
    
        public virtual mmtexam mmtexam { get; set; }
        public virtual mmtgroup mmtgroup { get; set; }
        public virtual mmtsection mmtsection { get; set; }
        public virtual mmttopic mmttopic { get; set; }
    }
}
