//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmtMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class mmtsection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mmtsection()
        {
            this.mmtgroups = new HashSet<mmtgroup>();
            this.mmtquestionbanks = new HashSet<mmtquestionbank>();
            this.mmttopics = new HashSet<mmttopic>();
        }
    
        public int secid { get; set; }
        [Required (ErrorMessage = "(Section name is required)")]
        [RegularExpression(@"([a-zA-Z0-9-_\s]+)", ErrorMessage = "(Only letters, numbers and space allowed)")]
        [StringLength(100)]
        public string sectionname { get; set; }
        public string sectiondesc { get; set; }
        public Nullable<int> sectionid { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<type> type { get; set; }
        public Nullable<int> score { get; set; }
        [NotMapped]
        public int review { get; set; }
        [NotMapped]
        public int compulsory { get; set; }
        [NotMapped]
        public int random { get; set; }
        [NotMapped]
        public int auto { get; set; }
        [NotMapped]
        public bool configured { get; set; }
        public virtual mmtexam mmtexam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mmtgroup> mmtgroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mmtquestionbank> mmtquestionbanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mmttopic> mmttopics { get; set; }
    }
}
